### ISSUE TITLE
Files missing in different stages of the pipeline

### ISSUE THREAD

**Issue by nipunperera** [DCAN-Labs/nhp-abcd-bids-pipeline#7]
**Hi, 

I've been trying to run the nhp-abcd-bids-pipeline for surface reconstruction using Macaque MR images. I have both T1w and T2w images. I have validated the BIDS file structure using the bids-validator.

Result of the bids-validator output**
--------------------------------------------------------------------------------------------------------------
bids-validator@1.5.2

	1: [WARN] The Authors field of dataset_description.json should contain an array of fields - with one author per field. This was triggered based on the presence of only one author field. Please ignore if all contributors are already properly listed. (code: 102 - TOO_FEW_AUTHORS)

	Please visit https://neurostars.org/search?q=TOO_FEW_AUTHORS for existing conversations about this issue.

        Summary:                Available Tasks:        Available Modalities: 
        9 Files, 15.33MB                                T1w                   
        1 - Subject                                     T2w                   
        1 - Session                                                           

	If you have any questions, please post on https://neurostars.org/tags/bids.
--------------------------------------------------------------------------------------------------------------

**I ran the pipeline using the following command.**
--------------------------------------------------------------------------------------------------------------
sudo docker run --rm 
-v /media/nipun/Data/Opitz-Lab/Research/TMS-Monkey/MRI/bids-willow:/bids_input:ro 
-v /media/nipun/Data/Opitz-Lab/Research/TMS-Monkey/MRI/pipeline:/output     
-v /usr/local/freesurfer/license.txt:/license     dcanlabs/nhp-abcd-bids-pipeline /bids_input /output --freesurfer-license=/license

--------------------------------------------------------------------------------------------------------------

The resulting console output is as follows.

--------------------------------------------------------------------------------------------------------------
running PreliminaryMasking
/opt/pipeline/PreliminaryMasking/macaque_masking.py \
    --path=/output/sub-Willow/ses-None/files \
    --t1 \
    /bids_input/sub-Willow/anat/sub-Willow_T1w.nii.gz \
    --t2 \
    /bids_input/sub-Willow/anat/sub-Willow_T2w.nii.gz \
    --func= \
    --fmapmag=NONE \
    --sshead=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_0.5mm.nii.gz \
    --ssbrain=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_0.5mm_brain.nii.gz \
    --verbose
running PreFreeSurfer
/opt/pipeline/PreFreeSurfer/PreFreeSurferPipeline.sh \
    --path=/output/sub-Willow/ses-None/files \
    --subject=Willow \
    --t1=/bids_input/sub-Willow/anat/sub-Willow_T1w.nii.gz \
    --t2=/bids_input/sub-Willow/anat/sub-Willow_T2w.nii.gz \
    --t1template=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_0.5mm.nii.gz \
    --t1templatebrain=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_0.5mm_brain.nii.gz \
    --t1template2mm=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_1.0mm.nii.gz \
    --t2template=/opt/pipeline/global/templates/MacaqueYerkes19_T2w_0.5mm.nii.gz \
    --t2templatebrain=/opt/pipeline/global/templates/MacaqueYerkes19_T2w_0.5mm_brain.nii.gz \
    --t2template2mm=/opt/pipeline/global/templates/MacaqueYerkes19_T2w_1.0mm.nii.gz \
    --templatemask=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_0.5mm_brain_mask.nii.gz \
    --template2mmmask=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_1.0mm_brain_mask.nii.gz \
    --brainsize=150 \
    --fnirtconfig=/opt/pipeline/global/config/T1_2_MNI152_2mm.cnf \
    --fmapmag=NONE \
    --fmapphase=NONE \
    --fmapgeneralelectric=NONE \
    --echodiff=NONE \
    --SEPhaseNeg=NONE \
    --SEPhasePos=NONE \
    --echospacing=NONE \
    --seunwarpdir=NONE \
    --t1samplespacing=0.000015 \
    --t2samplespacing=0.0000025 \
    --unwarpdir=z- \
    --gdcoeffs=NONE \
    --avgrdcmethod=NONE \
    --topupconfig=/opt/pipeline/global/config/b02b0.cnf \
    --useT2=true \
    --printcom= \
    --fmapmagbrain=NONE \
    --revepi=NONE \
    --multitemplatedir=NONE
found outputs from an earlier run of PreFreeSurfer
removing /output/sub-Willow/ses-None/files/T1w/T1w.nii.gz
removing /output/sub-Willow/ses-None/files/T1w/T1w_acpc.nii.gz
removing /output/sub-Willow/ses-None/files/T1w/xfms/acpc.mat
removing /output/sub-Willow/ses-None/files/T1w/T1w_acpc_brain.nii.gz
missing expected outputs from PreFreeSurfer
file not found: /output/sub-Willow/ses-None/files/T1w/T1w_acpc_brain_mask.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/T1w_acpc_dc_brain.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/T1w_acpc_dc_restore.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/T1w_acpc_dc_restore_brain.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/BiasField_acpc_dc.nii.gz
running FreeSurfer
/opt/pipeline/FreeSurfer/FreeGreyPipeline.sh \
    --subject=Willow \
    --subjectDIR=/output/sub-Willow/ses-None/files/T1w \
    --t1=/output/sub-Willow/ses-None/files/T1w/T1w_acpc_dc_restore.nii.gz \
    --t1brain=/output/sub-Willow/ses-None/files/T1w/T1w_acpc_dc_restore_brain.nii.gz \
    --t2=/output/sub-Willow/ses-None/files/T1w/T2w_acpc_dc_restore.nii.gz \
    --normalizationMethod=ADULT_GM_IP \
    --useT2=true \
    --aseg=/output/sub-Willow/ses-None/files/T1w/aseg_acpc.nii.gz \
    --gca=/opt/pipeline/global/templates/MacaqueYerkes19/RB_all_2008-03-26.gca \
    --maxThickness=5 \
    --printcom=
missing expected outputs from FreeSurfer
file not found: /output/sub-Willow/ses-None/files/T1w/T1w_acpc_dc_restore_brain_1mm.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/Willow/label/lh.aparc.a2009s.annot
file not found: /output/sub-Willow/ses-None/files/T1w/Willow/label/lh.aparc.annot
file not found: /output/sub-Willow/ses-None/files/T1w/Willow/label/rh.aparc.annot
file not found: /output/sub-Willow/ses-None/files/T1w/Willow/surf/lh.pial
file not found: /output/sub-Willow/ses-None/files/T1w/Willow/surf/lh.sphere
file not found: /output/sub-Willow/ses-None/files/T1w/Willow/surf/lh.sphere.reg
file not found: /output/sub-Willow/ses-None/files/T1w/Willow/surf/lh.white
file not found: /output/sub-Willow/ses-None/files/T1w/Willow/surf/rh.pial
file not found: /output/sub-Willow/ses-None/files/T1w/Willow/surf/rh.sphere
file not found: /output/sub-Willow/ses-None/files/T1w/Willow/surf/rh.sphere.reg
file not found: /output/sub-Willow/ses-None/files/T1w/Willow/surf/rh.white
running PostFreeSurfer
/opt/pipeline/PostFreeSurfer/PostFreeSurferPipeline.sh \
    --path=/output/sub-Willow/ses-None/files \
    --subject=Willow \
    --surfatlasdir=/opt/pipeline/global/templates/standard_mesh_atlases \
    --grayordinatesdir=/opt/pipeline/global/templates/91282_Greyordinates \
    --grayordinatesres=1.25 \
    --hiresmesh=164 \
    --lowresmesh=32 \
    --subcortgraylabels=/opt/pipeline/global/config/FreeSurferSubcorticalLabelTableLut.txt \
    --freesurferlabels=/opt/pipeline/global/config/FreeSurferAllLut.txt \
    --refmyelinmaps=/opt/pipeline/global/templates/standard_mesh_atlases/MacaqueYerkes19.MyelinMap_BC.164k_fs_LR.dscalar.nii \
    --regname=FS \
    --reference2mm=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_1.0mm.nii.gz \
    --reference2mmmask=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_1.0mm_brain_mask.nii.gz \
    --config=/opt/pipeline/global/config/T1_2_MNI152_2mm.cnf \
    --useT2=true \
    --t1template=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_0.5mm.nii.gz \
    --t1templatebrain=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_0.5mm_brain.nii.gz \
    --t1template2mm=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_1.0mm.nii.gz \
    --t2template=/opt/pipeline/global/templates/MacaqueYerkes19_T2w_0.5mm.nii.gz \
    --t2templatebrain=/opt/pipeline/global/templates/MacaqueYerkes19_T2w_0.5mm_brain.nii.gz \
    --t2template2mm=/opt/pipeline/global/templates/MacaqueYerkes19_T2w_1.0mm.nii.gz \
    --templatemask=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_0.5mm_brain_mask.nii.gz \
    --template2mmmask=/opt/pipeline/global/templates/MacaqueYerkes19_T1w_1.0mm_brain_mask.nii.gz \
    --printcom=
found outputs from an earlier run of PostFreeSurfer
removing /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage/Willow.L.def_sphere.164k_fs_L.surf.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage/Willow.L.sphere.164k_fs_L.surf.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage/Willow.R.def_sphere.164k_fs_R.surf.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage/Willow.R.sphere.164k_fs_R.surf.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.atlasroi.32k_fs_LR.shape.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.sphere.32k_fs_LR.surf.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.atlasroi.32k_fs_LR.shape.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.sphere.32k_fs_LR.surf.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/Willow.164k_fs_LR.wb.spec
removing /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.atlasroi.164k_fs_LR.shape.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.refsulc.164k_fs_LR.shape.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.sphere.164k_fs_LR.surf.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.atlasroi.164k_fs_LR.shape.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.refsulc.164k_fs_LR.shape.gii
removing /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.sphere.164k_fs_LR.surf.gii
missing expected outputs from PostFreeSurfer
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.ArealDistortion_FS.native.dscalar.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.aparc.a2009s.native.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.aparc.native.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.atlasroi.native.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.curvature.native.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.inflated.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.midthickness.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.pial.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.roi.native.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.sphere.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.sphere.reg.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.sphere.reg.reg_LR.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.sulc.native.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.thickness.native.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.very_inflated.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.L.white.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.aparc.a2009s.native.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.aparc.native.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.atlasroi.native.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.curvature.native.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.inflated.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.midthickness.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.pial.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.roi.native.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.sphere.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.sphere.reg.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.sphere.reg.reg_LR.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.sulc.native.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.thickness.native.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.very_inflated.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.R.white.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.aparc.a2009s.native.dlabel.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.aparc.native.dlabel.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.curvature.native.dscalar.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.native.wb.spec
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.sulc.native.dscalar.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Native/Willow.thickness.native.dscalar.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/aparc+aseg.nii.gz
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/aparc.a2009s+aseg.nii.gz
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.ArealDistortion_FS.32k_fs_LR.dscalar.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.ArealDistortion_FS.32k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.aparc.32k_fs_LR.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.aparc.a2009s.32k_fs_LR.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.curvature.32k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.inflated.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.midthickness.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.pial.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.sulc.32k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.thickness.32k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.very_inflated.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.L.white.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.ArealDistortion_FS.32k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.aparc.32k_fs_LR.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.aparc.a2009s.32k_fs_LR.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.curvature.32k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.inflated.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.midthickness.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.pial.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.sulc.32k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.thickness.32k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.very_inflated.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.R.white.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.aparc.32k_fs_LR.dlabel.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.aparc.a2009s.32k_fs_LR.dlabel.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.curvature.32k_fs_LR.dscalar.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.sulc.32k_fs_LR.dscalar.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/fsaverage_LR32k/Willow.thickness.32k_fs_LR.dscalar.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/ribbon.nii.gz
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/wmparc.nii.gz
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.ArealDistortion_FS.164k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.aparc.164k_fs_LR.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.aparc.a2009s.164k_fs_LR.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.curvature.164k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.inflated.164k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.midthickness.164k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.pial.164k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.sulc.164k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.thickness.164k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.very_inflated.164k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.L.white.164k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.ArealDistortion_FS.164k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.aparc.164k_fs_LR.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.aparc.a2009s.164k_fs_LR.label.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.curvature.164k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.inflated.164k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.midthickness.164k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.pial.164k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.sulc.164k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.thickness.164k_fs_LR.shape.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.very_inflated.164k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.R.white.164k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.aparc.164k_fs_LR.dlabel.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.aparc.a2009s.164k_fs_LR.dlabel.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.curvature.164k_fs_LR.dscalar.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.sulc.164k_fs_LR.dscalar.nii
file not found: /output/sub-Willow/ses-None/files/MNINonLinear/Willow.thickness.164k_fs_LR.dscalar.nii
file not found: /output/sub-Willow/ses-None/files/T1w/Native/Willow.L.inflated.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/Native/Willow.L.midthickness.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/Native/Willow.L.pial.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/Native/Willow.L.very_inflated.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/Native/Willow.L.white.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/Native/Willow.R.inflated.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/Native/Willow.R.midthickness.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/Native/Willow.R.pial.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/Native/Willow.R.very_inflated.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/Native/Willow.R.white.native.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/Native/Willow.native.wb.spec
file not found: /output/sub-Willow/ses-None/files/T1w/aparc+aseg.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/aparc+aseg_1mm.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/aparc.a2009s+aseg.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/aparc.a2009s+aseg_1mm.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/brainmask_fs_1mm.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/fsaverage_LR32k/Willow.32k_fs_LR.wb.spec
file not found: /output/sub-Willow/ses-None/files/T1w/fsaverage_LR32k/Willow.L.inflated.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/fsaverage_LR32k/Willow.L.midthickness.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/fsaverage_LR32k/Willow.L.pial.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/fsaverage_LR32k/Willow.L.very_inflated.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/fsaverage_LR32k/Willow.L.white.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/fsaverage_LR32k/Willow.R.inflated.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/fsaverage_LR32k/Willow.R.midthickness.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/fsaverage_LR32k/Willow.R.pial.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/fsaverage_LR32k/Willow.R.very_inflated.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/fsaverage_LR32k/Willow.R.white.32k_fs_LR.surf.gii
file not found: /output/sub-Willow/ses-None/files/T1w/ribbon.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/wmparc.nii.gz
file not found: /output/sub-Willow/ses-None/files/T1w/wmparc_1mm.nii.gz
Traceback (most recent call last):
  File "/app/run.py", line 334, in <module>
    _cli()
  File "/app/run.py", line 58, in _cli
    args.freesurfer_license)
  File "/app/run.py", line 330, in interface
    stage.run(ncpus)
  File "/app/pipelines.py", line 579, in run
    self.teardown(result)
  File "/app/pipelines.py", line 523, in teardown
    self.__class__.__name__)
Exception: error caught during stage: PostFreeSurfer

--------------------------------------------------------------------------------------------------------------

I appreciate if you could help me with this. Thank you

**Comment by PeterYuan1986** [comment]
> 

did you solve it? I have the same issue

**Comment by danjgale** [comment]
Also curious to know if either of you solved this problem? I am also having the same issue

**Comment by Lyl0519** [comment]
same issue :(
